namespace FamilyTogether.Mobile.Localization;

/// <summary>
/// Tablas de textos en castellano (es-ES) e ingles (en-US). Cada clave tiene que estar en las dos.
/// Los errores (<c>Err_&lt;codigo&gt;</c>) dicen la razon y que hacer (General 6.9).
/// </summary>
internal static class Strings
{
    public static readonly Dictionary<string, string> Es = new()
    {
        // ---------------------------------------------------------------- general
        ["AppName"] = "Family Together",
        ["Ok"] = "Aceptar",
        ["Cancel"] = "Cancelar",
        ["Close"] = "Cerrar",
        ["Save"] = "Guardar",
        ["Create"] = "Crear",
        ["Edit"] = "Editar",
        ["Delete"] = "Borrar",
        ["Refresh"] = "Actualizar",
        ["Loading"] = "Cargando…",
        ["Unknown"] = "(no se puede leer)",
        ["MeSuffix"] = "{0} (tú)",

        // ---------------------------------------------------------------- menú
        ["MenuMap"] = "Mapa",
        ["MenuGroups"] = "Grupos",
        ["MenuZones"] = "Zonas",
        ["MenuHistory"] = "Historial",
        ["MenuGuide"] = "Guía de configuración",
        ["MenuSettings"] = "Ajustes",
        ["MenuWhatsNew"] = "Novedades",
        ["MenuAbout"] = "Acerca de",

        // ---------------------------------------------------------------- bienvenida
        ["WelcomeTitle"] = "Bienvenida",
        ["WelcomeWhatTitle"] = "Qué hace Family Together",
        ["WelcomeWhatBody"] = "Las personas de un grupo cerrado (tu familia, tus amigos) ven dónde está cada una, sus recorridos de los últimos 30 días y reciben avisos al entrar o salir de las zonas que elijáis. Con el botón rojo mandas un SOS a tus grupos.",
        ["WelcomePrivacyTitle"] = "Qué sale de tu móvil",
        ["WelcomePrivacyBody"] = "Tu posición cuando te mueves 25 metros o más, la hora y la batería, también con la app cerrada. Tu nombre, tu avatar y tus coordenadas se cifran en el móvil con una clave que solo tienen los móviles de tu grupo: el servidor guarda datos que no puede leer. Para dibujar los recorridos por las calles se pide a OpenStreetMap el mapa de la zona, nunca tu recorrido. Puedes pausar cada grupo y borrar tu historial cuando quieras. No hace falta cuenta ni contraseña.",
        ["WelcomeYouTitle"] = "Cómo te verán",
        ["WelcomeContinue"] = "Continuar",
        ["DisplayNameLabel"] = "Tu nombre visible (obligatorio)",
        ["DisplayNamePlaceholder"] = "Por ejemplo, Ana",
        ["DisplayNameHint"] = "Es lo que verán los miembros de tus grupos. Lo puedes cambiar después en Ajustes.",
        ["DisplayNameRequired"] = "Escribe un nombre: es lo que verán los demás en el mapa. Puede ser tu nombre de pila o un apodo.",
        ["AvatarLabel"] = "Tu foto o avatar (opcional)",
        ["AvatarChoose"] = "Elegir foto",
        ["AvatarRemove"] = "Quitar foto",
        ["AvatarPick"] = "Elige una foto",
        ["NoServerTitle"] = "Servidor sin configurar",
        ["NoServerBody"] = "Esta compilación de Family Together no lleva la dirección de ningún servidor, así que no puede crear tu usuario ni compartir nada. La app no se ha roto: le falta la configuración.",
        ["NoServerWhat"] = "Qué hacer: instala la versión publicada. Si la compilas tú, rellena familytogether.local.props (hay un ejemplo junto al proyecto) y vuelve a compilar.",

        // ---------------------------------------------------------------- guía
        ["GuideStepOf"] = "Paso {0} de {1}",
        ["GuideBack"] = "Anterior",
        ["GuideNext"] = "Siguiente",
        ["GuideFinish"] = "Terminar",
        ["GuideDone"] = "Hecho",
        ["GuidePending"] = "Pendiente",
        ["GuideOptional"] = "Opcional",
        ["GuideIntroTitle"] = "Prepara tu móvil",
        ["GuideIntroBody"] = "Para que tu grupo vea tu posición también con la app cerrada, Android necesita unos permisos y que no la duerma para ahorrar batería. Son unos pocos pasos; cada uno tiene un botón que lo hace o que abre la pantalla donde se hace. Puedes volver a esta guía cuando quieras desde el menú.",
        ["GuidePreciseTitle"] = "Ubicación precisa",
        ["GuidePreciseBody"] = "Family Together envía tu posición cuando te mueves 25 metros o más, y descarta las lecturas imprecisas. Con la ubicación «aproximada» (unos 2 km) no saldría ninguna. Elige «Ubicación precisa».",
        ["GuidePreciseAction"] = "Permitir ubicación",
        ["GuideAlwaysTitle"] = "Permitir siempre",
        ["GuideAlwaysBody"] = "Para que tu grupo te vea con la app cerrada y tras reiniciar el móvil, la ubicación tiene que estar en «Permitir todo el tiempo». Android no lo ofrece en un diálogo: se abre Ajustes y ahí eliges Permisos > Ubicación > Permitir todo el tiempo.",
        ["GuideAlwaysAction"] = "Permitir todo el tiempo",
        ["GuideNotifTitle"] = "Notificaciones",
        ["GuideNotifBody"] = "Para recibir los SOS de tu grupo, los avisos de entrada y salida de zonas y las solicitudes para unirse. Android también muestra una notificación fija mientras se comparte tu ubicación.",
        ["GuideNotifAction"] = "Permitir notificaciones",
        ["GuideBatteryTitle"] = "Sin restricciones de batería",
        ["GuideBatteryBody"] = "Si Android duerme la app para ahorrar batería, tu grupo deja de verte y los avisos llegan tarde. Excluirla del ahorro de batería gasta muy poco: solo se envía cuando te mueves.",
        ["GuideBatteryAction"] = "Excluir del ahorro de batería",
        ["GuideAutostartTitle"] = "Inicio automático",
        ["GuideAutostartAction"] = "Abrir los ajustes del fabricante",
        ["GuideEndTitle"] = "Listo",
        ["GuideEndBody"] = "Ya está. Ahora crea un grupo o únete a uno con el código o el QR que te dé un administrador. Si algo deja de funcionar, vuelve a esta guía desde el menú: cada paso dice si está hecho.",
        ["OpenGuide"] = "Abrir la guía",

        // ---------------------------------------------------------------- mapa
        ["ChooseGroup"] = "Elige un grupo",
        ["ShowEveryone"] = "Ver a todos",
        ["NoGroupsTitle"] = "Aún no tienes grupos",
        ["NoGroupsBody"] = "Crea un grupo e invita a los tuyos, o únete a uno con el código o el QR que te dé un administrador.",
        ["GoToGroups"] = "Ir a Grupos",
        ["NoPositionYet"] = "Sin posición todavía",
        ["GroupNoKeyName"] = "Grupo sin clave en este móvil",
        ["KeyMissingTitle"] = "Clave del grupo",
        ["KeyMissingShort"] = "falta la clave",
        ["KeyMissingBanner"] = "Este móvil no tiene la clave de este grupo, así que no puede leer sus nombres ni posiciones. Se ha pedido a los demás miembros: llegará sola en cuanto alguno abra la app.",
        ["KeyMissingAction"] = "Pedir la clave otra vez",
        ["KeyMissingRequested"] = "Pedida. En cuanto otro miembro del grupo abra Family Together, este móvil recibirá la clave y verás el grupo.",
        ["SharingDenied"] = "No se está compartiendo tu ubicación: Family Together no tiene permiso. Abre la guía y concede la ubicación precisa.",
        ["SharingWhileInUse"] = "Tu grupo solo te ve con la app abierta: falta «Permitir todo el tiempo». Abre la guía para activarlo.",
        ["SharingStopped"] = "El servicio que comparte tu ubicación está parado. Abre la guía y comprueba la batería y el inicio automático.",
        ["SosPendingBanner"] = "Hay un SOS pendiente de enviar: se reintenta solo en cuanto haya conexión.",

        // ---------------------------------------------------------------- tiempos
        ["AgoNow"] = "ahora mismo",
        ["AgoMinutes"] = "hace {0} min",
        ["AgoHours"] = "hace {0} h",
        ["AgoDate"] = "el {0}",
        ["TomorrowAt"] = "mañana {0}",
        ["PausedUntil"] = "En pausa (hasta {0})",
        ["PausedIndefinite"] = "En pausa",
        ["BatteryPercent"] = "batería {0} %",

        // ---------------------------------------------------------------- SOS
        ["SosButton"] = "SOS",
        ["SosDescription"] = "Enviar un SOS a tus grupos",
        ["SosTitle"] = "SOS",
        ["SosSendingIn"] = "Enviando SOS en",
        ["SosCancelHint"] = "Pulsa Cancelar si ha sido sin querer.",
        ["SosCancel"] = "Cancelar",
        ["SosToGroups"] = "A estos grupos",
        ["SosToGroupsHint"] = "Desmarca los que no quieras avisar. Se envía con tu ubicación aunque estés en pausa.",
        ["SosNoGroups"] = "No estás en ningún grupo: no hay a quién avisar.",
        ["SosCancelled"] = "SOS cancelado",
        ["SosCancelledBody"] = "No se ha enviado nada.",
        ["SosLocating"] = "Buscando tu posición…",
        ["SosNotSent"] = "SOS no enviado",
        ["SosNoTargets"] = "No había ningún grupo marcado. Vuelve a pulsar SOS y deja marcado al menos uno.",
        ["SosNoLocation"] = "No se sabe dónde estás: el GPS no responde y no hay ninguna posición anterior. Activa la ubicación del móvil, sal a un sitio abierto y vuelve a pulsar SOS.",
        ["SosSent"] = "SOS enviado",
        ["SosSentBody"] = "Se ha avisado a los miembros de {0} grupo(s) con tu posición.",
        ["SosPending"] = "Pendiente, reintentando",
        ["SosPendingBody"] = "No hay conexión ahora mismo. El SOS está guardado en el móvil y se envía solo en cuanto vuelva la conexión, aunque cierres la app.",
        ["SosStale"] = "Sin GPS en este momento: se ha enviado tu última posición conocida ({0}).",
        ["BackToMap"] = "Volver al mapa",

        // ---------------------------------------------------------------- grupos
        ["MyGroupsTitle"] = "Mis grupos",
        ["MyRequestsTitle"] = "Mis solicitudes",
        ["RequestPending"] = "Solicitud pendiente de aprobación por un administrador.",
        ["RequestApprovedTitle"] = "Solicitud aprobada",
        ["RequestApprovedBody"] = "Ya eres miembro. Tu grupo empezará a ver tu posición en el mapa.",
        ["RequestRejectedTitle"] = "Solicitud rechazada",
        ["RequestRejectedBody"] = "Un administrador ha rechazado tu solicitud (o el grupo ya no existe). Si crees que es un error, pídele un código nuevo.",
        ["RoleAdmin"] = "Administrador",
        ["RoleMember"] = "Miembro",
        ["CreateGroup"] = "Crear grupo",
        ["GroupNamePrompt"] = "El nombre lo ven solo los miembros; viaja cifrado.",
        ["GroupNamePlaceholder"] = "Por ejemplo, Familia",
        ["GroupNameRequired"] = "Escribe un nombre para el grupo.",
        ["JoinTitle"] = "Unirse a un grupo",
        ["JoinWithCode"] = "Unirse con un código",
        ["Join"] = "Unirse",
        ["ScanQr"] = "Escanear QR",
        ["JoinHint"] = "El código y el QR los genera un administrador del grupo y caducan a los 5 minutos. Tu entrada tiene que aprobarla un administrador.",
        ["JoinCodePrompt"] = "Escribe el código de 8 caracteres que te ha dado un administrador.",
        ["JoinCodeInvalid"] = "Eso no es un código de invitación: son 8 letras y números (sin O, I, 0 ni 1). Revísalo o pide uno nuevo.",
        ["JoinConfirmCode"] = "¿Pedir entrar en el grupo con el código {0}?",
        ["JoinSent"] = "Solicitud enviada. Cuando un administrador la apruebe, el grupo aparecerá aquí y en el mapa.",
        ["ScanHint"] = "Apunta la cámara al QR que enseña el administrador.",
        ["ScanNoFrames"] = "La cámara no está dando imagen. Ciérrala y vuelve a abrirla; si sigue igual, escribe el código a mano.",
        ["ScanNotOurs"] = "Ese QR no es una invitación de FamilyTogether. Apunta al QR de la pantalla Invitar del administrador.",
        ["ScanNoCamera"] = "Sin permiso de cámara no se puede leer el QR. Puedes escribir el código a mano, o dar el permiso en Ajustes > Aplicaciones > Family Together > Permisos.",

        // ---------------------------------------------------------------- detalle de grupo
        ["GroupTitle"] = "Grupo",
        ["MembersTitle"] = "Miembros",
        ["RequestsTitle"] = "Solicitudes pendientes",
        ["RequestedAgo"] = "Pidió entrar {0}",
        ["Approve"] = "Aprobar",
        ["Reject"] = "Rechazar",
        ["Invite"] = "Invitar",
        ["MakeAdmin"] = "Hacer administrador",
        ["RemoveAdmin"] = "Quitar administrador",
        ["MakeAdminConfirm"] = "{0} podrá aprobar solicitudes, invitar, expulsar y nombrar administradores.",
        ["RemoveAdminConfirm"] = "{0} dejará de ser administrador y seguirá como miembro.",
        ["Kick"] = "Expulsar",
        ["KickConfirm"] = "{0} dejará de ver el grupo al momento y el grupo dejará de ver su posición. Para volver necesitará una invitación nueva.",
        ["MySharingTitle"] = "Mi ubicación en este grupo",
        ["SharingInGroup"] = "Compartiendo",
        ["Pause"] = "Pausar",
        ["Resume"] = "Reanudar",
        ["PauseHint"] = "Durante la pausa este grupo no recibe ni ve tus posiciones; tus otros grupos siguen igual. El SOS se envía aunque estés en pausa.",
        ["PauseOneHour"] = "1 hora",
        ["PauseEightHours"] = "8 horas",
        ["PauseTomorrow"] = "Hasta mañana a las 8:00",
        ["PauseIndefinite"] = "Hasta que la reanude",
        ["PauseChooseTime"] = "Hasta una hora…",
        ["PauseUntilChosen"] = "Pausar hasta esta hora (si ya ha pasado hoy, mañana):",
        ["PauseConfirm"] = "Pausar",
        ["LeaveGroup"] = "Abandonar el grupo",
        ["LeaveConfirm"] = "Dejarás de ver el grupo y el grupo dejará de ver tu posición. Para volver necesitarás una invitación nueva. Si eres el único miembro, el grupo se borra.",

        // ---------------------------------------------------------------- invitar
        ["InviteTitle"] = "Invitar",
        ["InviteHint"] = "Para unirse a «{0}»: escanea este QR desde Family Together (Grupos > Escanear QR) o escribe el código.",
        ["InviteHowTo"] = "Cada código sirve 5 minutos. Cuando alguien lo use, te llegará su solicitud para aprobarla.",
        ["InviteExpiresIn"] = "Caduca en {0}",
        ["InviteExpired"] = "Caducado: pide otro código",
        ["InviteNewCode"] = "Otro código",
        ["ShareCode"] = "Compartir el código",
        ["InviteShareText"] = "Únete a «{0}» en Family Together con el código {1} (caduca en 5 minutos) o abre {2}",

        // ---------------------------------------------------------------- zonas
        ["ZonesTitle"] = "Zonas del grupo",
        ["NewZone"] = "Nueva zona",
        ["EditZone"] = "Editar zona",
        ["NoZones"] = "Este grupo no tiene zonas. Crea una (casa, colegio, trabajo) para recibir avisos al entrar o salir.",
        ["NoGroupsWithKey"] = "No tienes ningún grupo que este móvil pueda leer. Crea uno o únete desde Grupos.",
        ["RadiusMeters"] = "Radio: {0} m",
        ["ZoneName"] = "Nombre de la zona",
        ["ZoneNamePlaceholder"] = "Por ejemplo, Casa",
        ["ZoneNameRequired"] = "Escribe un nombre para la zona: es lo que dirán los avisos.",
        ["ZoneTapHint"] = "Toca el mapa para poner el centro y ajusta el radio.",
        ["DeleteZoneConfirm"] = "¿Borrar la zona «{0}»? Se borra para todo el grupo, con sus avisos.",
        ["ZoneAlerts"] = "Avisos",
        ["ZoneAlertsHint"] = "Elige de quién y de qué zonas de «{0}» quieres un aviso al entrar o salir. Solo te avisará de lo que actives aquí.",
        ["ZoneAlertsNobody"] = "Aún no hay nadie más en el grupo.",
        ["AlertOnEnter"] = "Al entrar",
        ["AlertOnExit"] = "Al salir",

        // ---------------------------------------------------------------- historial
        ["ChooseMember"] = "Persona",
        ["TrackStart"] = "Inicio",
        ["TrackEnd"] = "Fin",
        ["TrackSummary"] = "{0} posiciones, de {1} a {2}",
        ["NoPositionsThatDay"] = "Sin posiciones ese día.",
        ["HistoryRetention"] = "Se guardan los últimos {0} días; lo anterior se borra solo.",
        ["SnapTracks"] = "Ajustar recorridos a calles y caminos",
        ["SnapTracksHint"] = "Consulta el mapa de OpenStreetMap por zonas, nunca tu recorrido: el ajuste se hace en tu móvil y solo cambia el dibujo.",
        ["SnapWorking"] = "Ajustando el recorrido a calles y caminos…",
        ["SnapDone"] = "Recorrido ajustado a calles y caminos (datos de OpenStreetMap).",
        ["SnapPartial"] = "Recorrido ajustado donde se ha podido; no se ha podido consultar el mapa de {0} de {1} zonas y esa parte va en línea recta.",
        ["SnapUnavailable"] = "No se ha podido consultar el mapa de calles: el recorrido va en línea recta entre posiciones.",
        ["ClearHistory"] = "Borrar mi historial",
        ["ClearHistoryHint"] = "Borra tus recorridos en todos tus grupos, también los que aún no se han enviado. Tus grupos seguirán viendo tu última posición en el mapa.",
        ["ClearHistoryConfirm"] = "Se borrarán todos tus recorridos en todos tus grupos, también los que aún no se han enviado. Tus grupos seguirán viendo tu última posición en el mapa. No se puede deshacer.",
        ["ClearHistoryDone"] = "Tu historial se ha borrado ({0} posiciones).",
        ["HistoryTitle"] = "Historial",

        // ---------------------------------------------------------------- ajustes
        ["LanguageTitle"] = "Idioma",
        ["LanguageSystem"] = "El del sistema",
        ["LanguageHint"] = "El cambio se aplica al momento.",
        ["ProfileTitle"] = "Mi nombre y avatar",
        ["ProfileHint"] = "Se actualiza en todos tus grupos, cifrado con la clave de cada uno.",
        ["AccountTitle"] = "Cuenta",
        ["AccountLinked"] = "Vinculada con {0}: si cambias de móvil, podrás recuperar tus grupos e historial.",
        ["AccountNotLinked"] = "Sin vincular. Si reinstalas la app o cambias de móvil, empezarás como un usuario nuevo. Vincula una cuenta para poder recuperarlo todo.",
        ["AccountNoProviders"] = "Esta compilación no tiene configurado Google ni Microsoft, así que no se puede vincular ni recuperar la cuenta.",
        ["LinkWith"] = "Vincular {0}",
        ["AccountLinkedDone"] = "Cuenta vinculada con {0}. En un móvil nuevo, usa «Recuperar mi cuenta en este móvil» con esa misma cuenta.",
        ["RecoverExplain"] = "¿Tienes un móvil nuevo? Si vinculaste Google o Microsoft en el anterior, trae aquí tus grupos, zonas e historial. El móvil anterior dejará de compartir tu ubicación.",
        ["RecoverAction"] = "Recuperar mi cuenta en este móvil",
        ["RecoverConfirm"] = "Solo funciona en un móvil sin grupos. Tus grupos pasarán a este móvil y el anterior dejará de compartir. Las claves de los grupos llegarán cuando otro miembro abra la app.",
        ["RecoverContinue"] = "Continuar",
        ["RecoverDone"] = "Cuenta recuperada. Tus grupos aparecerán en cuanto este móvil reciba sus claves de los demás miembros; no hace falta que hagas nada.",
        ["PermissionsTitle"] = "Permisos y batería",
        ["PermLocationAlways"] = "Ubicación: siempre",
        ["PermLocationWhileInUse"] = "Ubicación: solo con la app abierta",
        ["PermLocationDenied"] = "Ubicación: sin permiso",
        ["PermUnavailable"] = "Ubicación: no disponible en este dispositivo",
        ["SharingRunning"] = "compartiendo",
        ["SharingNotRunning"] = "parado",
        ["PermNotifOn"] = "Notificaciones: activadas",
        ["PermNotifOff"] = "Notificaciones: desactivadas",
        ["PermBatteryOk"] = "Batería: sin restricciones",
        ["PermBatteryRestricted"] = "Batería: con ahorro (puede retrasar los avisos)",

        // ---------------------------------------------------------------- novedades
        ["WhatsNewCurrent"] = "{0} (la instalada)",
        ["WhatsNewEmpty"] = "No hay novedades que enseñar.",
        ["WhatsNewOpen"] = "Ver las novedades",

        // ---------------------------------------------------------------- acerca de
        ["AboutDescription"] = "Localización familiar en grupos cerrados, con recorridos, zonas y SOS, cifrada de extremo a extremo.",
        ["Publisher"] = "Socratic",
        ["Contact"] = "Contacto",
        ["WriteAuthor"] = "Escribir al autor",
        ["ContactHint"] = "Dudas, errores o ideas: contesto a todo.",
        ["EmailCopied"] = "No hay aplicación de correo. Dirección copiada: {0}",
        ["LinkCopied"] = "No se pudo abrir el navegador. Enlace copiado: {0}",
        ["Privacy"] = "Privacidad",
        ["PrivacyText"] = "Tus coordenadas, tu nombre, tu avatar y los nombres de grupos y zonas se cifran en tu móvil con la clave del grupo antes de salir: el servidor no puede leerlos. Las posiciones se borran a los 30 días, y tú puedes borrar las tuyas cuando quieras en Ajustes o en Historial. Para dibujar los recorridos por las calles, el móvil pide a OpenStreetMap (Overpass) el mapa de calles de cuadrados fijos de unos 2 km, nunca tu recorrido, y lo guarda unos días; se puede apagar en Ajustes. Sin publicidad ni analítica.",
        ["PrivacyPolicy"] = "Política de privacidad",
        ["License"] = "Licencia",
        ["LicenseText"] = "Software libre con licencia MIT.",
        ["ThirdParty"] = "Mapa: MapLibre GL JS (BSD-3), teselas de OpenFreeMap y datos de OpenStreetMap (ODbL), también para ajustar los recorridos (consultados por Overpass). QR: ZXing.Net (Apache 2.0) y QRCoder (MIT).",
        ["LicenseLine"] = "Copyright © 2026 Socratic",
        ["LegalTitle"] = "Aviso legal",
        ["LegalText1"] = "Esta aplicación se ofrece «tal cual», sin garantías de ningún tipo. El autor no se hace responsable de los daños que pueda causar su uso.",
        ["LegalText2"] = "La posición depende del GPS, de la red y de los ajustes de batería del dispositivo: puede llegar tarde, ser imprecisa o no llegar.",
        ["WarningText"] = "Family Together no sustituye a los servicios de emergencia. En una emergencia, llama al 112.",

        // ---------------------------------------------------------------- avisos (Platforms\Android)
        ["ServiceNotifTitle"] = "Compartiendo tu ubicación",
        ["ServiceNotifText"] = "Tus grupos ven tu última posición. Puedes pausar cada grupo desde la app.",
        ["ChannelSos"] = "SOS",
        ["ChannelZones"] = "Zonas",
        ["ChannelRequests"] = "Solicitudes",
        ["ChannelService"] = "Compartir ubicación",
        ["NotifSosTitle"] = "SOS de {0}",
        ["NotifSosBody"] = "{0}: necesita ayuda. Toca para verle en el mapa.",
        ["NotifSosBodyStale"] = "{0}: necesita ayuda. Su posición es la última conocida, no la de ahora. Toca para verla.",
        ["NotifZoneEnterTitle"] = "{0} ha llegado a {1}",
        ["NotifZoneExitTitle"] = "{0} ha salido de {1}",
        ["NotifZoneBody"] = "Grupo {0}",
        ["NotifJoinTitle"] = "Solicitud para unirse",
        ["NotifJoinBody"] = "{0} quiere unirse a {1}. Toca para aprobar o rechazar.",
        ["NotifApprovedTitle"] = "Solicitud aprobada",
        ["NotifApprovedBody"] = "Ya eres miembro de {0}.",
        ["NotifRejectedTitle"] = "Solicitud rechazada",
        ["NotifRejectedBody"] = "Un administrador ha rechazado tu solicitud para unirte al grupo.",

        // ---------------------------------------------------------------- errores (razón + qué hacer)
        ["ErrorTitle"] = "No se ha podido hacer",
        ["ErrUnexpected"] = "Ha fallado algo que no se esperaba. La app sigue abierta y el error ha quedado registrado. Vuelve a intentarlo; si se repite, escríbenos desde Acerca de.",
        ["Err_network"] = "No hay conexión con el servidor. Comprueba que tienes datos o wifi y vuelve a intentarlo.",
        ["Err_unauthorized"] = "Tu sesión en este móvil ya no es válida (quizá recuperaste la cuenta en otro móvil). Cierra y abre la app; si sigue igual, usa «Recuperar mi cuenta en este móvil» en Ajustes.",
        ["Err_auth_required"] = "Tu sesión en este móvil ya no es válida. Cierra y abre la app; si sigue igual, usa «Recuperar mi cuenta en este móvil» en Ajustes.",
        ["Err_server"] = "El servidor ha dado un error. No es cosa de tu móvil: espera un momento y vuelve a intentarlo.",
        ["Err_not_configured"] = "Esta compilación no tiene configurado ese servicio. Instala la versión publicada de la app.",
        ["Err_provider_not_configured"] = "El servidor no tiene configurado ese proveedor de cuentas. Prueba con el otro (Google o Microsoft) o escríbenos desde Acerca de.",
        ["Err_key_missing"] = "Este móvil no tiene la clave de ese grupo, así que no puede cifrar lo que hace falta. Se ha pedido a los demás miembros: llegará en cuanto alguno abra la app.",
        ["Err_not_member"] = "Ya no eres miembro de ese grupo (te han expulsado o el grupo se ha borrado). Para volver, pide una invitación nueva.",
        ["Err_not_admin"] = "Eso solo lo puede hacer un administrador del grupo. Pídeselo a uno de ellos.",
        ["Err_expired"] = "El código ha caducado: solo sirve 5 minutos. Pide al administrador que genere otro.",
        ["Err_not_found"] = "Ese código no existe. Revisa que esté bien escrito (8 caracteres) o pide uno nuevo.",
        ["Err_already_member"] = "Ya eres miembro de ese grupo: lo tienes en Grupos y en el mapa.",
        ["Err_last_admin"] = "Eres el único administrador y hay más miembros. Nombra administrador a otra persona antes de salir o de quitarte el cargo.",
        ["Err_paused"] = "Estás en pausa en ese grupo. Reanúdalo para compartir tu posición.",
        ["Err_not_pending"] = "Esa solicitud ya estaba resuelta (quizá otro administrador se ha adelantado). Se actualiza la lista.",
        ["Err_already_linked"] = "Esa cuenta ya está vinculada a otro usuario de Family Together y no se fusionan. Usa otra cuenta, o recupérala en ese usuario con «Recuperar mi cuenta en este móvil».",
        ["Err_not_empty"] = "Este móvil ya tiene grupos, y recuperar solo funciona en un móvil sin grupos (nunca se mezclan dos usuarios). Abandona esos grupos o reinstala la app y recupera la cuenta antes de unirte a nada.",
        ["Err_not_linked"] = "Esa cuenta no está vinculada a ningún usuario de FamilyTogether. Comprueba que eliges la misma cuenta que vinculaste en el móvil anterior.",
        ["Err_no_link"] = "Esa cuenta no está vinculada a ningún usuario de FamilyTogether. Comprueba que eliges la misma cuenta que vinculaste en el móvil anterior.",
        ["Err_invalid_token"] = "El proveedor no ha confirmado tu identidad. Vuelve a intentarlo y elige la cuenta en la pantalla de Google o Microsoft.",
        ["Err_sign_in_failed"] = "No se ha podido iniciar sesión con esa cuenta. Vuelve a intentarlo y completa la pantalla de Google o Microsoft.",
        ["Err_bad_request"] = "El servidor no ha entendido la petición. Actualiza la app a la última versión y vuelve a intentarlo.",
        ["Err_secure_storage"] = "No se ha podido guardar en el almacén seguro del móvil. Reinicia el móvil y vuelve a intentarlo.",
        ["Err_cancelled"] = "Se ha cancelado antes de terminar. Vuelve a intentarlo cuando quieras.",
        ["Err_permission"] = "Falta un permiso para hacerlo. Dalo en Ajustes > Aplicaciones > Family Together > Permisos y vuelve a intentarlo.",
    };

    public static readonly Dictionary<string, string> En = new()
    {
        // ---------------------------------------------------------------- general
        ["AppName"] = "Family Together",
        ["Ok"] = "OK",
        ["Cancel"] = "Cancel",
        ["Close"] = "Close",
        ["Save"] = "Save",
        ["Create"] = "Create",
        ["Edit"] = "Edit",
        ["Delete"] = "Delete",
        ["Refresh"] = "Refresh",
        ["Loading"] = "Loading…",
        ["Unknown"] = "(cannot be read)",
        ["MeSuffix"] = "{0} (you)",

        // ---------------------------------------------------------------- menu
        ["MenuMap"] = "Map",
        ["MenuGroups"] = "Groups",
        ["MenuZones"] = "Zones",
        ["MenuHistory"] = "History",
        ["MenuGuide"] = "Setup guide",
        ["MenuSettings"] = "Settings",
        ["MenuWhatsNew"] = "What's new",
        ["MenuAbout"] = "About",

        // ---------------------------------------------------------------- welcome
        ["WelcomeTitle"] = "Welcome",
        ["WelcomeWhatTitle"] = "What Family Together does",
        ["WelcomeWhatBody"] = "The people in a closed group (your family, your friends) see where each other is, their routes from the last 30 days, and get alerts when someone arrives at or leaves the zones you choose. The red button sends an SOS to your groups.",
        ["WelcomePrivacyTitle"] = "What leaves your phone",
        ["WelcomePrivacyBody"] = "Your position whenever you move 25 metres or more, the time and the battery level, even with the app closed. Your name, your avatar and your coordinates are encrypted on the phone with a key that only your group's phones have: the server stores data it cannot read. To draw routes along the streets, the phone asks OpenStreetMap for the map of the area, never your route. You can pause each group and delete your history whenever you like. No account or password needed.",
        ["WelcomeYouTitle"] = "How others will see you",
        ["WelcomeContinue"] = "Continue",
        ["DisplayNameLabel"] = "Your display name (required)",
        ["DisplayNamePlaceholder"] = "For example, Anna",
        ["DisplayNameHint"] = "This is what your groups' members will see. You can change it later in Settings.",
        ["DisplayNameRequired"] = "Type a name: it is what the others will see on the map. It can be your first name or a nickname.",
        ["AvatarLabel"] = "Your photo or avatar (optional)",
        ["AvatarChoose"] = "Choose photo",
        ["AvatarRemove"] = "Remove photo",
        ["AvatarPick"] = "Choose a photo",
        ["NoServerTitle"] = "Server not configured",
        ["NoServerBody"] = "This build of Family Together does not include any server address, so it cannot create your user or share anything. The app is not broken: it is missing its configuration.",
        ["NoServerWhat"] = "What to do: install the published version. If you build it yourself, fill in familytogether.local.props (there is an example next to the project) and build again.",

        // ---------------------------------------------------------------- guide
        ["GuideStepOf"] = "Step {0} of {1}",
        ["GuideBack"] = "Back",
        ["GuideNext"] = "Next",
        ["GuideFinish"] = "Finish",
        ["GuideDone"] = "Done",
        ["GuidePending"] = "Pending",
        ["GuideOptional"] = "Optional",
        ["GuideIntroTitle"] = "Get your phone ready",
        ["GuideIntroBody"] = "For your group to see your position even with the app closed, Android needs a few permissions and must not put the app to sleep to save battery. It takes a few steps; each has a button that does it or opens the screen where it is done. You can come back to this guide any time from the menu.",
        ["GuidePreciseTitle"] = "Precise location",
        ["GuidePreciseBody"] = "Family Together sends your position when you move 25 metres or more, and discards inaccurate readings. With “approximate” location (about 2 km) nothing would be sent. Choose “Precise location”.",
        ["GuidePreciseAction"] = "Allow location",
        ["GuideAlwaysTitle"] = "Allow all the time",
        ["GuideAlwaysBody"] = "For your group to see you with the app closed and after a restart, location must be set to “Allow all the time”. Android does not offer it in a dialog: Settings opens and there you choose Permissions > Location > Allow all the time.",
        ["GuideAlwaysAction"] = "Allow all the time",
        ["GuideNotifTitle"] = "Notifications",
        ["GuideNotifBody"] = "To receive your group's SOS alerts, zone arrival and departure alerts, and requests to join. Android also shows a persistent notification while your location is being shared.",
        ["GuideNotifAction"] = "Allow notifications",
        ["GuideBatteryTitle"] = "No battery restrictions",
        ["GuideBatteryBody"] = "If Android puts the app to sleep to save battery, your group stops seeing you and alerts arrive late. Excluding it from battery optimisation costs very little: it only sends when you move.",
        ["GuideBatteryAction"] = "Exclude from battery optimisation",
        ["GuideAutostartTitle"] = "Autostart",
        ["GuideAutostartAction"] = "Open the manufacturer's settings",
        ["GuideEndTitle"] = "All set",
        ["GuideEndBody"] = "That's it. Now create a group or join one with the code or QR an admin gives you. If something stops working, come back to this guide from the menu: each step tells you whether it is done.",
        ["OpenGuide"] = "Open the guide",

        // ---------------------------------------------------------------- map
        ["ChooseGroup"] = "Choose a group",
        ["ShowEveryone"] = "Show everyone",
        ["NoGroupsTitle"] = "No groups yet",
        ["NoGroupsBody"] = "Create a group and invite your people, or join one with the code or QR an admin gives you.",
        ["GoToGroups"] = "Go to Groups",
        ["NoPositionYet"] = "No position yet",
        ["GroupNoKeyName"] = "Group without a key on this phone",
        ["KeyMissingTitle"] = "Group key",
        ["KeyMissingShort"] = "key missing",
        ["KeyMissingBanner"] = "This phone does not have this group's key, so it cannot read its names or positions. It has been requested from the other members: it will arrive by itself as soon as one of them opens the app.",
        ["KeyMissingAction"] = "Request the key again",
        ["KeyMissingRequested"] = "Requested. As soon as another group member opens Family Together, this phone will receive the key and you will see the group.",
        ["SharingDenied"] = "Your location is not being shared: Family Together has no permission. Open the guide and grant precise location.",
        ["SharingWhileInUse"] = "Your group only sees you while the app is open: “Allow all the time” is missing. Open the guide to turn it on.",
        ["SharingStopped"] = "The service that shares your location is stopped. Open the guide and check battery and autostart.",
        ["SosPendingBanner"] = "An SOS is waiting to be sent: it retries by itself as soon as there is a connection.",

        // ---------------------------------------------------------------- times
        ["AgoNow"] = "just now",
        ["AgoMinutes"] = "{0} min ago",
        ["AgoHours"] = "{0} h ago",
        ["AgoDate"] = "on {0}",
        ["TomorrowAt"] = "tomorrow {0}",
        ["PausedUntil"] = "Paused (until {0})",
        ["PausedIndefinite"] = "Paused",
        ["BatteryPercent"] = "battery {0}%",

        // ---------------------------------------------------------------- SOS
        ["SosButton"] = "SOS",
        ["SosDescription"] = "Send an SOS to your groups",
        ["SosTitle"] = "SOS",
        ["SosSendingIn"] = "Sending SOS in",
        ["SosCancelHint"] = "Tap Cancel if it was a mistake.",
        ["SosCancel"] = "Cancel",
        ["SosToGroups"] = "To these groups",
        ["SosToGroupsHint"] = "Untick the ones you don't want to alert. It is sent with your location even if you are paused.",
        ["SosNoGroups"] = "You are not in any group: there is nobody to alert.",
        ["SosCancelled"] = "SOS cancelled",
        ["SosCancelledBody"] = "Nothing has been sent.",
        ["SosLocating"] = "Finding your position…",
        ["SosNotSent"] = "SOS not sent",
        ["SosNoTargets"] = "No group was ticked. Tap SOS again and leave at least one ticked.",
        ["SosNoLocation"] = "Your location is unknown: GPS is not responding and there is no previous position. Turn on the phone's location, go somewhere open and tap SOS again.",
        ["SosSent"] = "SOS sent",
        ["SosSentBody"] = "The members of {0} group(s) have been alerted with your position.",
        ["SosPending"] = "Pending, retrying",
        ["SosPendingBody"] = "There is no connection right now. The SOS is stored on the phone and is sent by itself as soon as the connection returns, even if you close the app.",
        ["SosStale"] = "No GPS right now: your last known position ({0}) was sent.",
        ["BackToMap"] = "Back to the map",

        // ---------------------------------------------------------------- groups
        ["MyGroupsTitle"] = "My groups",
        ["MyRequestsTitle"] = "My requests",
        ["RequestPending"] = "Request waiting for an admin's approval.",
        ["RequestApprovedTitle"] = "Request approved",
        ["RequestApprovedBody"] = "You are now a member. Your group will start seeing your position on the map.",
        ["RequestRejectedTitle"] = "Request rejected",
        ["RequestRejectedBody"] = "An admin rejected your request (or the group no longer exists). If you think it is a mistake, ask them for a new code.",
        ["RoleAdmin"] = "Admin",
        ["RoleMember"] = "Member",
        ["CreateGroup"] = "Create group",
        ["GroupNamePrompt"] = "Only members see the name; it travels encrypted.",
        ["GroupNamePlaceholder"] = "For example, Family",
        ["GroupNameRequired"] = "Type a name for the group.",
        ["JoinTitle"] = "Join a group",
        ["JoinWithCode"] = "Join with a code",
        ["Join"] = "Join",
        ["ScanQr"] = "Scan QR",
        ["JoinHint"] = "The code and the QR are created by a group admin and expire after 5 minutes. An admin has to approve your entry.",
        ["JoinCodePrompt"] = "Type the 8-character code an admin gave you.",
        ["JoinCodeInvalid"] = "That is not an invitation code: it is 8 letters and digits (no O, I, 0 or 1). Check it or ask for a new one.",
        ["JoinConfirmCode"] = "Request to join the group with code {0}?",
        ["JoinSent"] = "Request sent. When an admin approves it, the group will appear here and on the map.",
        ["ScanHint"] = "Point the camera at the QR the admin is showing.",
        ["ScanNoFrames"] = "The camera is not giving any image. Close it and open it again; if nothing changes, type the code by hand.",
        ["ScanNotOurs"] = "That QR is not a Family Together invitation. Point at the QR on the admin's Invite screen.",
        ["ScanNoCamera"] = "Without camera permission the QR cannot be read. You can type the code by hand, or grant the permission in Settings > Apps > Family Together > Permissions.",

        // ---------------------------------------------------------------- group detail
        ["GroupTitle"] = "Group",
        ["MembersTitle"] = "Members",
        ["RequestsTitle"] = "Pending requests",
        ["RequestedAgo"] = "Asked to join {0}",
        ["Approve"] = "Approve",
        ["Reject"] = "Reject",
        ["Invite"] = "Invite",
        ["MakeAdmin"] = "Make admin",
        ["RemoveAdmin"] = "Remove admin",
        ["MakeAdminConfirm"] = "{0} will be able to approve requests, invite, remove members and appoint admins.",
        ["RemoveAdminConfirm"] = "{0} will stop being an admin and stay as a member.",
        ["Kick"] = "Remove from group",
        ["KickConfirm"] = "{0} will stop seeing the group right away and the group will stop seeing their position. To come back they will need a new invitation.",
        ["MySharingTitle"] = "My location in this group",
        ["SharingInGroup"] = "Sharing",
        ["Pause"] = "Pause",
        ["Resume"] = "Resume",
        ["PauseHint"] = "While paused this group neither receives nor sees your positions; your other groups are not affected. SOS is sent even when paused.",
        ["PauseOneHour"] = "1 hour",
        ["PauseEightHours"] = "8 hours",
        ["PauseTomorrow"] = "Until tomorrow at 8:00",
        ["PauseIndefinite"] = "Until I resume it",
        ["PauseChooseTime"] = "Until a time…",
        ["PauseUntilChosen"] = "Pause until this time (if it has already passed today, tomorrow):",
        ["PauseConfirm"] = "Pause",
        ["LeaveGroup"] = "Leave the group",
        ["LeaveConfirm"] = "You will stop seeing the group and the group will stop seeing your position. To come back you will need a new invitation. If you are the only member, the group is deleted.",

        // ---------------------------------------------------------------- invite
        ["InviteTitle"] = "Invite",
        ["InviteHint"] = "To join “{0}”: scan this QR from Family Together (Groups > Scan QR) or type the code.",
        ["InviteHowTo"] = "Each code works for 5 minutes. When someone uses it, you will get their request to approve.",
        ["InviteExpiresIn"] = "Expires in {0}",
        ["InviteExpired"] = "Expired: get another code",
        ["InviteNewCode"] = "Another code",
        ["ShareCode"] = "Share the code",
        ["InviteShareText"] = "Join “{0}” on Family Together with code {1} (expires in 5 minutes) or open {2}",

        // ---------------------------------------------------------------- zones
        ["ZonesTitle"] = "Group zones",
        ["NewZone"] = "New zone",
        ["EditZone"] = "Edit zone",
        ["NoZones"] = "This group has no zones. Create one (home, school, work) to get alerts on arrival or departure.",
        ["NoGroupsWithKey"] = "You have no group this phone can read. Create one or join one from Groups.",
        ["RadiusMeters"] = "Radius: {0} m",
        ["ZoneName"] = "Zone name",
        ["ZoneNamePlaceholder"] = "For example, Home",
        ["ZoneNameRequired"] = "Type a name for the zone: it is what the alerts will say.",
        ["ZoneTapHint"] = "Tap the map to set the centre and adjust the radius.",
        ["DeleteZoneConfirm"] = "Delete the zone “{0}”? It is deleted for the whole group, along with its alerts.",
        ["ZoneAlerts"] = "Alerts",
        ["ZoneAlertsHint"] = "Choose whose arrivals and departures in which zones of “{0}” you want to be alerted about. You will only be alerted about what you turn on here.",
        ["ZoneAlertsNobody"] = "There is nobody else in the group yet.",
        ["AlertOnEnter"] = "On arrival",
        ["AlertOnExit"] = "On departure",

        // ---------------------------------------------------------------- history
        ["ChooseMember"] = "Person",
        ["TrackStart"] = "Start",
        ["TrackEnd"] = "End",
        ["TrackSummary"] = "{0} positions, from {1} to {2}",
        ["NoPositionsThatDay"] = "No positions that day.",
        ["HistoryRetention"] = "The last {0} days are kept; anything older is deleted automatically.",
        ["SnapTracks"] = "Snap routes to streets and paths",
        ["SnapTracksHint"] = "Looks up the OpenStreetMap street map by area, never your route: the snapping happens on your phone and only changes the drawing.",
        ["SnapWorking"] = "Snapping the route to streets and paths…",
        ["SnapDone"] = "Route snapped to streets and paths (OpenStreetMap data).",
        ["SnapPartial"] = "Route snapped where possible; the map for {0} of {1} areas could not be looked up and that part is drawn as a straight line.",
        ["SnapUnavailable"] = "The street map could not be looked up: the route is drawn as straight lines between positions.",
        ["ClearHistory"] = "Delete my history",
        ["ClearHistoryHint"] = "Deletes your routes in all your groups, including those not sent yet. Your groups will still see your last position on the map.",
        ["ClearHistoryConfirm"] = "All your routes in all your groups will be deleted, including those not sent yet. Your groups will still see your last position on the map. This cannot be undone.",
        ["ClearHistoryDone"] = "Your history has been deleted ({0} positions).",
        ["HistoryTitle"] = "History",

        // ---------------------------------------------------------------- settings
        ["LanguageTitle"] = "Language",
        ["LanguageSystem"] = "System language",
        ["LanguageHint"] = "The change applies right away.",
        ["ProfileTitle"] = "My name and avatar",
        ["ProfileHint"] = "It is updated in all your groups, encrypted with each group's key.",
        ["AccountTitle"] = "Account",
        ["AccountLinked"] = "Linked with {0}: if you change phones, you can recover your groups and history.",
        ["AccountNotLinked"] = "Not linked. If you reinstall the app or change phones, you will start as a new user. Link an account to be able to recover everything.",
        ["AccountNoProviders"] = "This build has neither Google nor Microsoft configured, so the account cannot be linked or recovered.",
        ["LinkWith"] = "Link {0}",
        ["AccountLinkedDone"] = "Account linked with {0}. On a new phone, use “Recover my account on this phone” with that same account.",
        ["RecoverExplain"] = "New phone? If you linked Google or Microsoft on the old one, bring your groups, zones and history here. The old phone will stop sharing your location.",
        ["RecoverAction"] = "Recover my account on this phone",
        ["RecoverConfirm"] = "It only works on a phone with no groups. Your groups will move to this phone and the old one will stop sharing. The group keys will arrive when another member opens the app.",
        ["RecoverContinue"] = "Continue",
        ["RecoverDone"] = "Account recovered. Your groups will appear as soon as this phone receives their keys from the other members; you do not need to do anything.",
        ["PermissionsTitle"] = "Permissions and battery",
        ["PermLocationAlways"] = "Location: all the time",
        ["PermLocationWhileInUse"] = "Location: only while the app is open",
        ["PermLocationDenied"] = "Location: no permission",
        ["PermUnavailable"] = "Location: not available on this device",
        ["SharingRunning"] = "sharing",
        ["SharingNotRunning"] = "stopped",
        ["PermNotifOn"] = "Notifications: on",
        ["PermNotifOff"] = "Notifications: off",
        ["PermBatteryOk"] = "Battery: unrestricted",
        ["PermBatteryRestricted"] = "Battery: optimised (alerts may be delayed)",

        // ---------------------------------------------------------------- what's new
        ["WhatsNewCurrent"] = "{0} (installed)",
        ["WhatsNewEmpty"] = "Nothing new to show.",
        ["WhatsNewOpen"] = "See what's new",

        // ---------------------------------------------------------------- about
        ["AboutDescription"] = "Family location in closed groups, with routes, zones and SOS, end-to-end encrypted.",
        ["Publisher"] = "Socratic",
        ["Contact"] = "Contact",
        ["WriteAuthor"] = "Write to the author",
        ["ContactHint"] = "Questions, bugs or ideas: I answer everything.",
        ["EmailCopied"] = "There is no email app. Address copied: {0}",
        ["LinkCopied"] = "The browser could not be opened. Link copied: {0}",
        ["Privacy"] = "Privacy",
        ["PrivacyText"] = "Your coordinates, your name, your avatar and the names of groups and zones are encrypted on your phone with the group key before leaving it: the server cannot read them. Positions are deleted after 30 days, and you can delete yours whenever you like in Settings or History. To draw routes along the streets, the phone asks OpenStreetMap (Overpass) for the street map of fixed squares of about 2 km, never your route, and keeps it for a few days; you can turn this off in Settings. No ads, no analytics.",
        ["PrivacyPolicy"] = "Privacy policy",
        ["License"] = "License",
        ["LicenseText"] = "Free software under the MIT license.",
        ["ThirdParty"] = "Map: MapLibre GL JS (BSD-3), OpenFreeMap tiles and OpenStreetMap data (ODbL), also used to snap routes (looked up through Overpass). QR: ZXing.Net (Apache 2.0) and QRCoder (MIT).",
        ["LicenseLine"] = "Copyright © 2026 Socratic",
        ["LegalTitle"] = "Legal notice",
        ["LegalText1"] = "This application is provided “as is”, without warranties of any kind. The author is not liable for any damage its use may cause.",
        ["LegalText2"] = "Positions depend on GPS, the network and the device's battery settings: they may arrive late, be inaccurate or not arrive at all.",
        ["WarningText"] = "Family Together is not a substitute for emergency services. In an emergency, call 112.",

        // ---------------------------------------------------------------- notifications (Platforms\Android)
        ["ServiceNotifTitle"] = "Sharing your location",
        ["ServiceNotifText"] = "Your groups see your last position. You can pause each group from the app.",
        ["ChannelSos"] = "SOS",
        ["ChannelZones"] = "Zones",
        ["ChannelRequests"] = "Requests",
        ["ChannelService"] = "Location sharing",
        ["NotifSosTitle"] = "SOS from {0}",
        ["NotifSosBody"] = "{0}: needs help. Tap to see them on the map.",
        ["NotifSosBodyStale"] = "{0}: needs help. The position is the last known one, not the current one. Tap to see it.",
        ["NotifZoneEnterTitle"] = "{0} arrived at {1}",
        ["NotifZoneExitTitle"] = "{0} left {1}",
        ["NotifZoneBody"] = "Group {0}",
        ["NotifJoinTitle"] = "Request to join",
        ["NotifJoinBody"] = "{0} wants to join {1}. Tap to approve or reject.",
        ["NotifApprovedTitle"] = "Request approved",
        ["NotifApprovedBody"] = "You are now a member of {0}.",
        ["NotifRejectedTitle"] = "Request rejected",
        ["NotifRejectedBody"] = "An admin rejected your request to join the group.",

        // ---------------------------------------------------------------- errors (reason + what to do)
        ["ErrorTitle"] = "Could not be done",
        ["ErrUnexpected"] = "Something unexpected failed. The app is still open and the error has been logged. Try again; if it happens again, write to us from About.",
        ["Err_network"] = "There is no connection to the server. Check that you have mobile data or Wi-Fi and try again.",
        ["Err_unauthorized"] = "Your session on this phone is no longer valid (perhaps you recovered the account on another phone). Close and reopen the app; if nothing changes, use “Recover my account on this phone” in Settings.",
        ["Err_auth_required"] = "Your session on this phone is no longer valid. Close and reopen the app; if nothing changes, use “Recover my account on this phone” in Settings.",
        ["Err_server"] = "The server returned an error. It is not your phone's fault: wait a moment and try again.",
        ["Err_not_configured"] = "This build does not have that service configured. Install the published version of the app.",
        ["Err_provider_not_configured"] = "The server does not have that account provider configured. Try the other one (Google or Microsoft) or write to us from About.",
        ["Err_key_missing"] = "This phone does not have that group's key, so it cannot encrypt what is needed. It has been requested from the other members: it will arrive as soon as one of them opens the app.",
        ["Err_not_member"] = "You are no longer a member of that group (you were removed or the group was deleted). To come back, ask for a new invitation.",
        ["Err_not_admin"] = "Only a group admin can do that. Ask one of them.",
        ["Err_expired"] = "The code has expired: it only works for 5 minutes. Ask the admin to create another one.",
        ["Err_not_found"] = "That code does not exist. Check it is typed correctly (8 characters) or ask for a new one.",
        ["Err_already_member"] = "You are already a member of that group: it is in Groups and on the map.",
        ["Err_last_admin"] = "You are the only admin and there are other members. Make someone else an admin before leaving or giving up the role.",
        ["Err_paused"] = "You are paused in that group. Resume it to share your position.",
        ["Err_not_pending"] = "That request was already resolved (perhaps another admin got there first). The list is being refreshed.",
        ["Err_already_linked"] = "That account is already linked to another Family Together user and users are never merged. Use another account, or recover it on that user with “Recover my account on this phone”.",
        ["Err_not_empty"] = "This phone already has groups, and recovery only works on a phone with no groups (two users are never mixed). Leave those groups, or reinstall the app and recover the account before joining anything.",
        ["Err_not_linked"] = "That account is not linked to any Family Together user. Make sure you choose the same account you linked on the old phone.",
        ["Err_no_link"] = "That account is not linked to any Family Together user. Make sure you choose the same account you linked on the old phone.",
        ["Err_invalid_token"] = "The provider did not confirm your identity. Try again and choose the account on the Google or Microsoft screen.",
        ["Err_sign_in_failed"] = "Signing in with that account failed. Try again and complete the Google or Microsoft screen.",
        ["Err_bad_request"] = "The server did not understand the request. Update the app to the latest version and try again.",
        ["Err_secure_storage"] = "Saving to the phone's secure storage failed. Restart the phone and try again.",
        ["Err_cancelled"] = "It was cancelled before finishing. Try again whenever you like.",
        ["Err_permission"] = "A permission is missing. Grant it in Settings > Apps > Family Together > Permissions and try again.",
    };
}
